version: '3.4'

services:
  mfe-dashboard:
    container_name: app-mfe-dashboard
    image: xcarlosr/mfe-dashboard:latest
    # build:
    #   context: .
    #   dockerfile: /apps/dashboard/Dockerfile
    restart: always
    ports:
      - "4200:80"
    networks:
      - rest

  mfe-login:
    container_name: app-mfe-login
    image: xcarlosr/mfe-login:latest
    # image: mfe-login-app
    # build:
    #   context: .
    #   dockerfile: /apps/login/Dockerfile
    restart: always
    ports:
      - "4201:80"
    networks:
      - rest
    depends_on:
      - mfe-dashboard

networks:
  rest:
    driver: bridge
