pipeline {
  agent any
  tools { nodejs "node" }

  environment {
    imageName = "xcarlosr/mfe-login"
    dockerhubId = 'dockerhub'
    dockerImage = ''
    appLoginPath = "**/apps/login/**"
    existNodeModelues = fileExists "${WORKSPACE}/node_modules"

  }

  stages {
        stage("Updade Source"){
            steps {
                // cleanWs()
                git url: 'https://github.com/xcarlosr/mfe-poc.git', branch: 'master'
            }
        }

        stage('Validated change app Login') {
            when { changeset appLoginPath }
            stages {
                stage('NPM Install') {
                    when { equals expected: false, actual: existNodeModelues }
                    steps {
                        script {
        					echo 'executando NPM I'
        					sh 'npm i'
                        }
                    }
                }

                stage('Build Login App ') {
                    steps {
                        script {
                            sh 'npx nx run login:build:development --skip-nx-cache'
                        }
                    }
                }
                stage('Validating Unit Test ') {
                    steps {
                        script {
                          sh 'npx nx test login'
                        }
                    }
                }

                stage('Validating Code lint ') {
                    steps {
                        script {
                          sh 'npx nx lint login'
                        }
                    }
                }

                stage('Docker') {
                    stages {
                        stage('Create Image') {
                            steps {
                              script {
                                dockerImage = docker.build("$imageName:$BUILD_NUMBER","-f ./apps/login/Dockerfile .")
                              }
                            }
                        }

                        stage('Push Image') {
                            steps {
                                echo "Push Image..."
                                script {
                                      docker.withRegistry('', dockerhubId){
                                      dockerImage.push('latest')
                                      dockerImage.push("$BUILD_NUMBER")
                                    }
                                }
                            }
                        }

                        stage('Remove Unused docker image') {
                            steps{
                                echo "Remove Unused docker image..."
                                sh "docker rmi $imageName:latest"
                                sh "docker rmi $imageName:$BUILD_NUMBER"
                            }
                        }
                    }
                }
            }
        }

        stage("Final Pipe"){
            steps {
                echo 'finalizado a PIPE'

            }
        }
   }
}
